apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prod: higher ceiling, conservative cooldown, PodDisruptionBudget, larger
# resource envelope.
resources:
  - ../../base
  - ../../rabbitmq
  - ../../keda
  - pdb.yaml

namespace: keda-demo

images:
  - name: ghcr.io/bhuv01/keda-queue-worker
    newName: ghcr.io/bhuv01/keda-queue-worker
    newTag: latest # CI replaces with the immutable git-SHA tag on release

patches:
  - path: patch-scaledobject.yaml
    target:
      group: keda.sh
      version: v1alpha1
      kind: ScaledObject
      name: queue-worker
  - path: patch-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: queue-worker
