apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-worker
  namespace: keda-demo
  labels:
    app.kubernetes.io/name: queue-worker
    app.kubernetes.io/part-of: keda-queue-demo
automountServiceAccountToken: false
